# Generated by Django 4.2.5 on 2023-10-11 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='disney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=25)),
                ('cartoon', models.CharField(max_length=25)),
                ('character', models.CharField(max_length=25)),
                ('time', models.TimeField()),
            ],
        ),
    ]
